/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module cpu(i_clk, i_rst_n, i_i_valid_inst, i_i_inst, i_d_valid_data, i_d_data, o_i_valid_addr, o_i_addr, o_d_w_data, o_d_w_addr, o_d_r_addr, o_d_MemRead, o_d_MemWrite, o_finish);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire [2:0] _028_;
  wire [63:0] _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire [63:0] \EXMEM.i_alu_data1 ;
  wire [63:0] \EXMEM.i_alu_out ;
  wire \EXMEM.i_clk ;
  wire [31:0] \EXMEM.i_inst ;
  wire \EXMEM.i_memRead ;
  wire \EXMEM.i_memToReg ;
  wire \EXMEM.i_memWrite ;
  wire [4:0] \EXMEM.i_rd_addr ;
  wire \EXMEM.i_regWrite ;
  wire [63:0] \EXMEM.i_rs2_data ;
  wire \EXMEM.i_rst_n ;
  reg [63:0] \EXMEM.o_alu_data1 ;
  reg [63:0] \EXMEM.o_alu_out ;
  reg [31:0] \EXMEM.o_inst ;
  reg \EXMEM.o_memRead ;
  reg \EXMEM.o_memToReg ;
  reg \EXMEM.o_memWrite ;
  reg [4:0] \EXMEM.o_rd_addr ;
  reg \EXMEM.o_regWrite ;
  reg [63:0] \EXMEM.o_rs2_data ;
  wire \IDEX.o_inst ;
  wire \IDEX.o_memRead ;
  wire \IDEX.o_memToReg ;
  wire \IDEX.o_memWrite ;
  wire \IDEX.o_regWrite ;
  wire \IFID.o_next_inst ;
  wire \alu.o_data ;
  wire \alu_data1_choose.o_data ;
  wire \control_unit.i_nop ;
  wire [6:0] \control_unit.i_opcode ;
  wire [1:0] \control_unit.o_aluOp ;
  wire \control_unit.o_aluSrc ;
  wire \control_unit.o_branch ;
  wire \control_unit.o_finish ;
  wire \control_unit.o_memRead ;
  wire \control_unit.o_memToReg ;
  wire \control_unit.o_memWrite ;
  wire \control_unit.o_regWrite ;
  wire \forwardB.o_data ;
  wire \hazard_detector.o_hazard ;
  wire \hazard_detector.o_nop ;
  input i_clk;
  input [63:0] i_d_data;
  input i_d_valid_data;
  input [31:0] i_i_inst;
  input i_i_valid_inst;
  input i_rst_n;
  output o_d_MemRead;
  output o_d_MemWrite;
  wire [63:0] o_d_addr;
  output [63:0] o_d_r_addr;
  output [63:0] o_d_w_addr;
  output [63:0] o_d_w_data;
  output o_finish;
  output [63:0] o_i_addr;
  output o_i_valid_addr;
  reg [2:0] \pc.clk_cnt ;
  wire \pc.i_change ;
  wire \pc.i_clk ;
  wire [63:0] \pc.i_inst_addr ;
  wire \pc.i_no_hazard ;
  wire \pc.i_rst_n ;
  reg [63:0] \pc.o_inst_addr ;
  reg \pc.o_valid_inst_addr ;
  wire \pc_choose.o_data ;
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [0] <= 0;
    else
      \EXMEM.o_inst [0] <= \EXMEM.i_inst [0];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [1] <= 0;
    else
      \EXMEM.o_inst [1] <= \EXMEM.i_inst [1];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [2] <= 0;
    else
      \EXMEM.o_inst [2] <= \EXMEM.i_inst [2];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [3] <= 0;
    else
      \EXMEM.o_inst [3] <= \EXMEM.i_inst [3];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [4] <= 0;
    else
      \EXMEM.o_inst [4] <= \EXMEM.i_inst [4];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [5] <= 0;
    else
      \EXMEM.o_inst [5] <= \EXMEM.i_inst [5];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [6] <= 0;
    else
      \EXMEM.o_inst [6] <= \EXMEM.i_inst [6];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [7] <= 0;
    else
      \EXMEM.o_inst [7] <= \EXMEM.i_inst [7];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [8] <= 0;
    else
      \EXMEM.o_inst [8] <= \EXMEM.i_inst [8];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [9] <= 0;
    else
      \EXMEM.o_inst [9] <= \EXMEM.i_inst [9];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [10] <= 0;
    else
      \EXMEM.o_inst [10] <= \EXMEM.i_inst [10];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [11] <= 0;
    else
      \EXMEM.o_inst [11] <= \EXMEM.i_inst [11];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [12] <= 0;
    else
      \EXMEM.o_inst [12] <= \EXMEM.i_inst [12];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [13] <= 0;
    else
      \EXMEM.o_inst [13] <= \EXMEM.i_inst [13];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [14] <= 0;
    else
      \EXMEM.o_inst [14] <= \EXMEM.i_inst [14];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [15] <= 0;
    else
      \EXMEM.o_inst [15] <= \EXMEM.i_inst [15];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [16] <= 0;
    else
      \EXMEM.o_inst [16] <= \EXMEM.i_inst [16];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [17] <= 0;
    else
      \EXMEM.o_inst [17] <= \EXMEM.i_inst [17];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [18] <= 0;
    else
      \EXMEM.o_inst [18] <= \EXMEM.i_inst [18];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [19] <= 0;
    else
      \EXMEM.o_inst [19] <= \EXMEM.i_inst [19];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [20] <= 0;
    else
      \EXMEM.o_inst [20] <= \EXMEM.i_inst [20];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [21] <= 0;
    else
      \EXMEM.o_inst [21] <= \EXMEM.i_inst [21];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [22] <= 0;
    else
      \EXMEM.o_inst [22] <= \EXMEM.i_inst [22];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [23] <= 0;
    else
      \EXMEM.o_inst [23] <= \EXMEM.i_inst [23];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [24] <= 0;
    else
      \EXMEM.o_inst [24] <= \EXMEM.i_inst [24];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [25] <= 0;
    else
      \EXMEM.o_inst [25] <= \EXMEM.i_inst [25];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [26] <= 0;
    else
      \EXMEM.o_inst [26] <= \EXMEM.i_inst [26];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [27] <= 0;
    else
      \EXMEM.o_inst [27] <= \EXMEM.i_inst [27];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [28] <= 0;
    else
      \EXMEM.o_inst [28] <= \EXMEM.i_inst [28];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [29] <= 0;
    else
      \EXMEM.o_inst [29] <= \EXMEM.i_inst [29];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [30] <= 0;
    else
      \EXMEM.o_inst [30] <= \EXMEM.i_inst [30];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_inst [31] <= 0;
    else
      \EXMEM.o_inst [31] <= \EXMEM.i_inst [31];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_memRead  <= 0;
    else
      \EXMEM.o_memRead  <= \EXMEM.i_memRead ;
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_memToReg  <= 0;
    else
      \EXMEM.o_memToReg  <= \EXMEM.i_memToReg ;
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_memWrite  <= 0;
    else
      \EXMEM.o_memWrite  <= \EXMEM.i_memWrite ;
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_regWrite  <= 0;
    else
      \EXMEM.o_regWrite  <= \EXMEM.i_regWrite ;
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [0] <= 0;
    else
      \EXMEM.o_rs2_data [0] <= \EXMEM.i_rs2_data [0];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [1] <= 0;
    else
      \EXMEM.o_rs2_data [1] <= \EXMEM.i_rs2_data [1];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [2] <= 0;
    else
      \EXMEM.o_rs2_data [2] <= \EXMEM.i_rs2_data [2];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [3] <= 0;
    else
      \EXMEM.o_rs2_data [3] <= \EXMEM.i_rs2_data [3];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [4] <= 0;
    else
      \EXMEM.o_rs2_data [4] <= \EXMEM.i_rs2_data [4];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [5] <= 0;
    else
      \EXMEM.o_rs2_data [5] <= \EXMEM.i_rs2_data [5];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [6] <= 0;
    else
      \EXMEM.o_rs2_data [6] <= \EXMEM.i_rs2_data [6];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [7] <= 0;
    else
      \EXMEM.o_rs2_data [7] <= \EXMEM.i_rs2_data [7];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [8] <= 0;
    else
      \EXMEM.o_rs2_data [8] <= \EXMEM.i_rs2_data [8];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [9] <= 0;
    else
      \EXMEM.o_rs2_data [9] <= \EXMEM.i_rs2_data [9];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [10] <= 0;
    else
      \EXMEM.o_rs2_data [10] <= \EXMEM.i_rs2_data [10];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [11] <= 0;
    else
      \EXMEM.o_rs2_data [11] <= \EXMEM.i_rs2_data [11];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [12] <= 0;
    else
      \EXMEM.o_rs2_data [12] <= \EXMEM.i_rs2_data [12];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [13] <= 0;
    else
      \EXMEM.o_rs2_data [13] <= \EXMEM.i_rs2_data [13];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [14] <= 0;
    else
      \EXMEM.o_rs2_data [14] <= \EXMEM.i_rs2_data [14];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [15] <= 0;
    else
      \EXMEM.o_rs2_data [15] <= \EXMEM.i_rs2_data [15];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [16] <= 0;
    else
      \EXMEM.o_rs2_data [16] <= \EXMEM.i_rs2_data [16];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [17] <= 0;
    else
      \EXMEM.o_rs2_data [17] <= \EXMEM.i_rs2_data [17];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [18] <= 0;
    else
      \EXMEM.o_rs2_data [18] <= \EXMEM.i_rs2_data [18];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [19] <= 0;
    else
      \EXMEM.o_rs2_data [19] <= \EXMEM.i_rs2_data [19];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [20] <= 0;
    else
      \EXMEM.o_rs2_data [20] <= \EXMEM.i_rs2_data [20];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [21] <= 0;
    else
      \EXMEM.o_rs2_data [21] <= \EXMEM.i_rs2_data [21];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [22] <= 0;
    else
      \EXMEM.o_rs2_data [22] <= \EXMEM.i_rs2_data [22];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [23] <= 0;
    else
      \EXMEM.o_rs2_data [23] <= \EXMEM.i_rs2_data [23];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [24] <= 0;
    else
      \EXMEM.o_rs2_data [24] <= \EXMEM.i_rs2_data [24];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [25] <= 0;
    else
      \EXMEM.o_rs2_data [25] <= \EXMEM.i_rs2_data [25];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [26] <= 0;
    else
      \EXMEM.o_rs2_data [26] <= \EXMEM.i_rs2_data [26];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [27] <= 0;
    else
      \EXMEM.o_rs2_data [27] <= \EXMEM.i_rs2_data [27];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [28] <= 0;
    else
      \EXMEM.o_rs2_data [28] <= \EXMEM.i_rs2_data [28];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [29] <= 0;
    else
      \EXMEM.o_rs2_data [29] <= \EXMEM.i_rs2_data [29];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [30] <= 0;
    else
      \EXMEM.o_rs2_data [30] <= \EXMEM.i_rs2_data [30];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [31] <= 0;
    else
      \EXMEM.o_rs2_data [31] <= \EXMEM.i_rs2_data [31];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [32] <= 0;
    else
      \EXMEM.o_rs2_data [32] <= \EXMEM.i_rs2_data [32];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [33] <= 0;
    else
      \EXMEM.o_rs2_data [33] <= \EXMEM.i_rs2_data [33];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [34] <= 0;
    else
      \EXMEM.o_rs2_data [34] <= \EXMEM.i_rs2_data [34];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [35] <= 0;
    else
      \EXMEM.o_rs2_data [35] <= \EXMEM.i_rs2_data [35];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [36] <= 0;
    else
      \EXMEM.o_rs2_data [36] <= \EXMEM.i_rs2_data [36];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [37] <= 0;
    else
      \EXMEM.o_rs2_data [37] <= \EXMEM.i_rs2_data [37];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [38] <= 0;
    else
      \EXMEM.o_rs2_data [38] <= \EXMEM.i_rs2_data [38];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [39] <= 0;
    else
      \EXMEM.o_rs2_data [39] <= \EXMEM.i_rs2_data [39];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [40] <= 0;
    else
      \EXMEM.o_rs2_data [40] <= \EXMEM.i_rs2_data [40];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [41] <= 0;
    else
      \EXMEM.o_rs2_data [41] <= \EXMEM.i_rs2_data [41];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [42] <= 0;
    else
      \EXMEM.o_rs2_data [42] <= \EXMEM.i_rs2_data [42];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [43] <= 0;
    else
      \EXMEM.o_rs2_data [43] <= \EXMEM.i_rs2_data [43];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [44] <= 0;
    else
      \EXMEM.o_rs2_data [44] <= \EXMEM.i_rs2_data [44];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [45] <= 0;
    else
      \EXMEM.o_rs2_data [45] <= \EXMEM.i_rs2_data [45];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [46] <= 0;
    else
      \EXMEM.o_rs2_data [46] <= \EXMEM.i_rs2_data [46];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [47] <= 0;
    else
      \EXMEM.o_rs2_data [47] <= \EXMEM.i_rs2_data [47];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [48] <= 0;
    else
      \EXMEM.o_rs2_data [48] <= \EXMEM.i_rs2_data [48];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [49] <= 0;
    else
      \EXMEM.o_rs2_data [49] <= \EXMEM.i_rs2_data [49];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [50] <= 0;
    else
      \EXMEM.o_rs2_data [50] <= \EXMEM.i_rs2_data [50];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [51] <= 0;
    else
      \EXMEM.o_rs2_data [51] <= \EXMEM.i_rs2_data [51];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [52] <= 0;
    else
      \EXMEM.o_rs2_data [52] <= \EXMEM.i_rs2_data [52];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [53] <= 0;
    else
      \EXMEM.o_rs2_data [53] <= \EXMEM.i_rs2_data [53];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [54] <= 0;
    else
      \EXMEM.o_rs2_data [54] <= \EXMEM.i_rs2_data [54];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [55] <= 0;
    else
      \EXMEM.o_rs2_data [55] <= \EXMEM.i_rs2_data [55];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [56] <= 0;
    else
      \EXMEM.o_rs2_data [56] <= \EXMEM.i_rs2_data [56];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [57] <= 0;
    else
      \EXMEM.o_rs2_data [57] <= \EXMEM.i_rs2_data [57];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [58] <= 0;
    else
      \EXMEM.o_rs2_data [58] <= \EXMEM.i_rs2_data [58];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [59] <= 0;
    else
      \EXMEM.o_rs2_data [59] <= \EXMEM.i_rs2_data [59];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [60] <= 0;
    else
      \EXMEM.o_rs2_data [60] <= \EXMEM.i_rs2_data [60];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [61] <= 0;
    else
      \EXMEM.o_rs2_data [61] <= \EXMEM.i_rs2_data [61];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [62] <= 0;
    else
      \EXMEM.o_rs2_data [62] <= \EXMEM.i_rs2_data [62];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rs2_data [63] <= 0;
    else
      \EXMEM.o_rs2_data [63] <= \EXMEM.i_rs2_data [63];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [0] <= 0;
    else
      \EXMEM.o_alu_out [0] <= \EXMEM.i_alu_out [0];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [1] <= 0;
    else
      \EXMEM.o_alu_out [1] <= \EXMEM.i_alu_out [1];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [2] <= 0;
    else
      \EXMEM.o_alu_out [2] <= \EXMEM.i_alu_out [2];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [3] <= 0;
    else
      \EXMEM.o_alu_out [3] <= \EXMEM.i_alu_out [3];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [4] <= 0;
    else
      \EXMEM.o_alu_out [4] <= \EXMEM.i_alu_out [4];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [5] <= 0;
    else
      \EXMEM.o_alu_out [5] <= \EXMEM.i_alu_out [5];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [6] <= 0;
    else
      \EXMEM.o_alu_out [6] <= \EXMEM.i_alu_out [6];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [7] <= 0;
    else
      \EXMEM.o_alu_out [7] <= \EXMEM.i_alu_out [7];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [8] <= 0;
    else
      \EXMEM.o_alu_out [8] <= \EXMEM.i_alu_out [8];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [9] <= 0;
    else
      \EXMEM.o_alu_out [9] <= \EXMEM.i_alu_out [9];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [10] <= 0;
    else
      \EXMEM.o_alu_out [10] <= \EXMEM.i_alu_out [10];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [11] <= 0;
    else
      \EXMEM.o_alu_out [11] <= \EXMEM.i_alu_out [11];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [12] <= 0;
    else
      \EXMEM.o_alu_out [12] <= \EXMEM.i_alu_out [12];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [13] <= 0;
    else
      \EXMEM.o_alu_out [13] <= \EXMEM.i_alu_out [13];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [14] <= 0;
    else
      \EXMEM.o_alu_out [14] <= \EXMEM.i_alu_out [14];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [15] <= 0;
    else
      \EXMEM.o_alu_out [15] <= \EXMEM.i_alu_out [15];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [16] <= 0;
    else
      \EXMEM.o_alu_out [16] <= \EXMEM.i_alu_out [16];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [17] <= 0;
    else
      \EXMEM.o_alu_out [17] <= \EXMEM.i_alu_out [17];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [18] <= 0;
    else
      \EXMEM.o_alu_out [18] <= \EXMEM.i_alu_out [18];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [19] <= 0;
    else
      \EXMEM.o_alu_out [19] <= \EXMEM.i_alu_out [19];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [20] <= 0;
    else
      \EXMEM.o_alu_out [20] <= \EXMEM.i_alu_out [20];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [21] <= 0;
    else
      \EXMEM.o_alu_out [21] <= \EXMEM.i_alu_out [21];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [22] <= 0;
    else
      \EXMEM.o_alu_out [22] <= \EXMEM.i_alu_out [22];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [23] <= 0;
    else
      \EXMEM.o_alu_out [23] <= \EXMEM.i_alu_out [23];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [24] <= 0;
    else
      \EXMEM.o_alu_out [24] <= \EXMEM.i_alu_out [24];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [25] <= 0;
    else
      \EXMEM.o_alu_out [25] <= \EXMEM.i_alu_out [25];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [26] <= 0;
    else
      \EXMEM.o_alu_out [26] <= \EXMEM.i_alu_out [26];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [27] <= 0;
    else
      \EXMEM.o_alu_out [27] <= \EXMEM.i_alu_out [27];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [28] <= 0;
    else
      \EXMEM.o_alu_out [28] <= \EXMEM.i_alu_out [28];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [29] <= 0;
    else
      \EXMEM.o_alu_out [29] <= \EXMEM.i_alu_out [29];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [30] <= 0;
    else
      \EXMEM.o_alu_out [30] <= \EXMEM.i_alu_out [30];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [31] <= 0;
    else
      \EXMEM.o_alu_out [31] <= \EXMEM.i_alu_out [31];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [32] <= 0;
    else
      \EXMEM.o_alu_out [32] <= \EXMEM.i_alu_out [32];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [33] <= 0;
    else
      \EXMEM.o_alu_out [33] <= \EXMEM.i_alu_out [33];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [34] <= 0;
    else
      \EXMEM.o_alu_out [34] <= \EXMEM.i_alu_out [34];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [35] <= 0;
    else
      \EXMEM.o_alu_out [35] <= \EXMEM.i_alu_out [35];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [36] <= 0;
    else
      \EXMEM.o_alu_out [36] <= \EXMEM.i_alu_out [36];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [37] <= 0;
    else
      \EXMEM.o_alu_out [37] <= \EXMEM.i_alu_out [37];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [38] <= 0;
    else
      \EXMEM.o_alu_out [38] <= \EXMEM.i_alu_out [38];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [39] <= 0;
    else
      \EXMEM.o_alu_out [39] <= \EXMEM.i_alu_out [39];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [40] <= 0;
    else
      \EXMEM.o_alu_out [40] <= \EXMEM.i_alu_out [40];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [41] <= 0;
    else
      \EXMEM.o_alu_out [41] <= \EXMEM.i_alu_out [41];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [42] <= 0;
    else
      \EXMEM.o_alu_out [42] <= \EXMEM.i_alu_out [42];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [43] <= 0;
    else
      \EXMEM.o_alu_out [43] <= \EXMEM.i_alu_out [43];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [44] <= 0;
    else
      \EXMEM.o_alu_out [44] <= \EXMEM.i_alu_out [44];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [45] <= 0;
    else
      \EXMEM.o_alu_out [45] <= \EXMEM.i_alu_out [45];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [46] <= 0;
    else
      \EXMEM.o_alu_out [46] <= \EXMEM.i_alu_out [46];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [47] <= 0;
    else
      \EXMEM.o_alu_out [47] <= \EXMEM.i_alu_out [47];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [48] <= 0;
    else
      \EXMEM.o_alu_out [48] <= \EXMEM.i_alu_out [48];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [49] <= 0;
    else
      \EXMEM.o_alu_out [49] <= \EXMEM.i_alu_out [49];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [50] <= 0;
    else
      \EXMEM.o_alu_out [50] <= \EXMEM.i_alu_out [50];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [51] <= 0;
    else
      \EXMEM.o_alu_out [51] <= \EXMEM.i_alu_out [51];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [52] <= 0;
    else
      \EXMEM.o_alu_out [52] <= \EXMEM.i_alu_out [52];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [53] <= 0;
    else
      \EXMEM.o_alu_out [53] <= \EXMEM.i_alu_out [53];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [54] <= 0;
    else
      \EXMEM.o_alu_out [54] <= \EXMEM.i_alu_out [54];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [55] <= 0;
    else
      \EXMEM.o_alu_out [55] <= \EXMEM.i_alu_out [55];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [56] <= 0;
    else
      \EXMEM.o_alu_out [56] <= \EXMEM.i_alu_out [56];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [57] <= 0;
    else
      \EXMEM.o_alu_out [57] <= \EXMEM.i_alu_out [57];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [58] <= 0;
    else
      \EXMEM.o_alu_out [58] <= \EXMEM.i_alu_out [58];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [59] <= 0;
    else
      \EXMEM.o_alu_out [59] <= \EXMEM.i_alu_out [59];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [60] <= 0;
    else
      \EXMEM.o_alu_out [60] <= \EXMEM.i_alu_out [60];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [61] <= 0;
    else
      \EXMEM.o_alu_out [61] <= \EXMEM.i_alu_out [61];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [62] <= 0;
    else
      \EXMEM.o_alu_out [62] <= \EXMEM.i_alu_out [62];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_out [63] <= 0;
    else
      \EXMEM.o_alu_out [63] <= \EXMEM.i_alu_out [63];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [0] <= 0;
    else
      \EXMEM.o_alu_data1 [0] <= \EXMEM.i_alu_data1 [0];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [1] <= 0;
    else
      \EXMEM.o_alu_data1 [1] <= \EXMEM.i_alu_data1 [1];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [2] <= 0;
    else
      \EXMEM.o_alu_data1 [2] <= \EXMEM.i_alu_data1 [2];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [3] <= 0;
    else
      \EXMEM.o_alu_data1 [3] <= \EXMEM.i_alu_data1 [3];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [4] <= 0;
    else
      \EXMEM.o_alu_data1 [4] <= \EXMEM.i_alu_data1 [4];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [5] <= 0;
    else
      \EXMEM.o_alu_data1 [5] <= \EXMEM.i_alu_data1 [5];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [6] <= 0;
    else
      \EXMEM.o_alu_data1 [6] <= \EXMEM.i_alu_data1 [6];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [7] <= 0;
    else
      \EXMEM.o_alu_data1 [7] <= \EXMEM.i_alu_data1 [7];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [8] <= 0;
    else
      \EXMEM.o_alu_data1 [8] <= \EXMEM.i_alu_data1 [8];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [9] <= 0;
    else
      \EXMEM.o_alu_data1 [9] <= \EXMEM.i_alu_data1 [9];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [10] <= 0;
    else
      \EXMEM.o_alu_data1 [10] <= \EXMEM.i_alu_data1 [10];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [11] <= 0;
    else
      \EXMEM.o_alu_data1 [11] <= \EXMEM.i_alu_data1 [11];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [12] <= 0;
    else
      \EXMEM.o_alu_data1 [12] <= \EXMEM.i_alu_data1 [12];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [13] <= 0;
    else
      \EXMEM.o_alu_data1 [13] <= \EXMEM.i_alu_data1 [13];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [14] <= 0;
    else
      \EXMEM.o_alu_data1 [14] <= \EXMEM.i_alu_data1 [14];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [15] <= 0;
    else
      \EXMEM.o_alu_data1 [15] <= \EXMEM.i_alu_data1 [15];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [16] <= 0;
    else
      \EXMEM.o_alu_data1 [16] <= \EXMEM.i_alu_data1 [16];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [17] <= 0;
    else
      \EXMEM.o_alu_data1 [17] <= \EXMEM.i_alu_data1 [17];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [18] <= 0;
    else
      \EXMEM.o_alu_data1 [18] <= \EXMEM.i_alu_data1 [18];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [19] <= 0;
    else
      \EXMEM.o_alu_data1 [19] <= \EXMEM.i_alu_data1 [19];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [20] <= 0;
    else
      \EXMEM.o_alu_data1 [20] <= \EXMEM.i_alu_data1 [20];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [21] <= 0;
    else
      \EXMEM.o_alu_data1 [21] <= \EXMEM.i_alu_data1 [21];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [22] <= 0;
    else
      \EXMEM.o_alu_data1 [22] <= \EXMEM.i_alu_data1 [22];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [23] <= 0;
    else
      \EXMEM.o_alu_data1 [23] <= \EXMEM.i_alu_data1 [23];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [24] <= 0;
    else
      \EXMEM.o_alu_data1 [24] <= \EXMEM.i_alu_data1 [24];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [25] <= 0;
    else
      \EXMEM.o_alu_data1 [25] <= \EXMEM.i_alu_data1 [25];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [26] <= 0;
    else
      \EXMEM.o_alu_data1 [26] <= \EXMEM.i_alu_data1 [26];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [27] <= 0;
    else
      \EXMEM.o_alu_data1 [27] <= \EXMEM.i_alu_data1 [27];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [28] <= 0;
    else
      \EXMEM.o_alu_data1 [28] <= \EXMEM.i_alu_data1 [28];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [29] <= 0;
    else
      \EXMEM.o_alu_data1 [29] <= \EXMEM.i_alu_data1 [29];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [30] <= 0;
    else
      \EXMEM.o_alu_data1 [30] <= \EXMEM.i_alu_data1 [30];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [31] <= 0;
    else
      \EXMEM.o_alu_data1 [31] <= \EXMEM.i_alu_data1 [31];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [32] <= 0;
    else
      \EXMEM.o_alu_data1 [32] <= \EXMEM.i_alu_data1 [32];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [33] <= 0;
    else
      \EXMEM.o_alu_data1 [33] <= \EXMEM.i_alu_data1 [33];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [34] <= 0;
    else
      \EXMEM.o_alu_data1 [34] <= \EXMEM.i_alu_data1 [34];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [35] <= 0;
    else
      \EXMEM.o_alu_data1 [35] <= \EXMEM.i_alu_data1 [35];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [36] <= 0;
    else
      \EXMEM.o_alu_data1 [36] <= \EXMEM.i_alu_data1 [36];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [37] <= 0;
    else
      \EXMEM.o_alu_data1 [37] <= \EXMEM.i_alu_data1 [37];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [38] <= 0;
    else
      \EXMEM.o_alu_data1 [38] <= \EXMEM.i_alu_data1 [38];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [39] <= 0;
    else
      \EXMEM.o_alu_data1 [39] <= \EXMEM.i_alu_data1 [39];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [40] <= 0;
    else
      \EXMEM.o_alu_data1 [40] <= \EXMEM.i_alu_data1 [40];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [41] <= 0;
    else
      \EXMEM.o_alu_data1 [41] <= \EXMEM.i_alu_data1 [41];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [42] <= 0;
    else
      \EXMEM.o_alu_data1 [42] <= \EXMEM.i_alu_data1 [42];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [43] <= 0;
    else
      \EXMEM.o_alu_data1 [43] <= \EXMEM.i_alu_data1 [43];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [44] <= 0;
    else
      \EXMEM.o_alu_data1 [44] <= \EXMEM.i_alu_data1 [44];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [45] <= 0;
    else
      \EXMEM.o_alu_data1 [45] <= \EXMEM.i_alu_data1 [45];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [46] <= 0;
    else
      \EXMEM.o_alu_data1 [46] <= \EXMEM.i_alu_data1 [46];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [47] <= 0;
    else
      \EXMEM.o_alu_data1 [47] <= \EXMEM.i_alu_data1 [47];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [48] <= 0;
    else
      \EXMEM.o_alu_data1 [48] <= \EXMEM.i_alu_data1 [48];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [49] <= 0;
    else
      \EXMEM.o_alu_data1 [49] <= \EXMEM.i_alu_data1 [49];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [50] <= 0;
    else
      \EXMEM.o_alu_data1 [50] <= \EXMEM.i_alu_data1 [50];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [51] <= 0;
    else
      \EXMEM.o_alu_data1 [51] <= \EXMEM.i_alu_data1 [51];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [52] <= 0;
    else
      \EXMEM.o_alu_data1 [52] <= \EXMEM.i_alu_data1 [52];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [53] <= 0;
    else
      \EXMEM.o_alu_data1 [53] <= \EXMEM.i_alu_data1 [53];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [54] <= 0;
    else
      \EXMEM.o_alu_data1 [54] <= \EXMEM.i_alu_data1 [54];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [55] <= 0;
    else
      \EXMEM.o_alu_data1 [55] <= \EXMEM.i_alu_data1 [55];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [56] <= 0;
    else
      \EXMEM.o_alu_data1 [56] <= \EXMEM.i_alu_data1 [56];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [57] <= 0;
    else
      \EXMEM.o_alu_data1 [57] <= \EXMEM.i_alu_data1 [57];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [58] <= 0;
    else
      \EXMEM.o_alu_data1 [58] <= \EXMEM.i_alu_data1 [58];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [59] <= 0;
    else
      \EXMEM.o_alu_data1 [59] <= \EXMEM.i_alu_data1 [59];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [60] <= 0;
    else
      \EXMEM.o_alu_data1 [60] <= \EXMEM.i_alu_data1 [60];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [61] <= 0;
    else
      \EXMEM.o_alu_data1 [61] <= \EXMEM.i_alu_data1 [61];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [62] <= 0;
    else
      \EXMEM.o_alu_data1 [62] <= \EXMEM.i_alu_data1 [62];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_alu_data1 [63] <= 0;
    else
      \EXMEM.o_alu_data1 [63] <= \EXMEM.i_alu_data1 [63];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rd_addr [0] <= 0;
    else
      \EXMEM.o_rd_addr [0] <= \EXMEM.i_rd_addr [0];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rd_addr [1] <= 0;
    else
      \EXMEM.o_rd_addr [1] <= \EXMEM.i_rd_addr [1];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rd_addr [2] <= 0;
    else
      \EXMEM.o_rd_addr [2] <= \EXMEM.i_rd_addr [2];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rd_addr [3] <= 0;
    else
      \EXMEM.o_rd_addr [3] <= \EXMEM.i_rd_addr [3];
  always @(posedge \EXMEM.i_clk  or negedge \EXMEM.i_rst_n )
    if (!\EXMEM.i_rst_n )
      \EXMEM.o_rd_addr [4] <= 0;
    else
      \EXMEM.o_rd_addr [4] <= \EXMEM.i_rd_addr [4];
  assign _000_ = ~(\control_unit.i_opcode [1] & \control_unit.i_opcode [0]);
  assign _001_ = \control_unit.i_opcode [3] | \control_unit.i_opcode [2];
  assign _002_ = _001_ | _000_;
  assign _003_ = ~\control_unit.i_opcode [6];
  assign _004_ = \control_unit.i_opcode [4] | \control_unit.i_opcode [5];
  assign _005_ = _003_ & ~(_004_);
  assign _006_ = _002_ | ~(_005_);
  assign _007_ = \control_unit.i_opcode [5] | ~(\control_unit.i_opcode [4]);
  assign _008_ = _003_ & ~(_007_);
  assign _009_ = _002_ | ~(_008_);
  assign _010_ = _009_ & _006_;
  assign _011_ = ~(\control_unit.i_opcode [4] & \control_unit.i_opcode [5]);
  assign _012_ = _011_ | \control_unit.i_opcode [6];
  assign _013_ = _012_ | _002_;
  assign \control_unit.o_regWrite  = ~((_013_ & _010_) | \control_unit.i_nop );
  assign _014_ = \control_unit.i_opcode [4] | ~(\control_unit.i_opcode [5]);
  assign _015_ = _014_ | \control_unit.i_opcode [6];
  assign _016_ = _015_ | _002_;
  assign _017_ = _016_ & _006_;
  assign \control_unit.o_aluSrc  = ~((_017_ & _009_) | \control_unit.i_nop );
  assign _018_ = ~\control_unit.i_nop ;
  assign \control_unit.o_memWrite  = _018_ & ~(_016_);
  assign _019_ = _014_ | _003_;
  assign _020_ = ~(_019_ | _002_);
  assign \control_unit.o_aluOp [0] = ~((_016_ & _013_) | \control_unit.i_nop );
  assign _021_ = ~((_019_ & _012_) | _002_);
  assign _022_ = _021_ | ~(_016_);
  assign _023_ = ~(_022_ & _021_);
  assign \control_unit.o_aluOp [1] = _018_ & ~(_023_);
  assign \control_unit.o_memRead  = _018_ & ~(_006_);
  assign \control_unit.o_branch  = _020_ & ~(\control_unit.i_nop );
  assign _024_ = ~(\control_unit.i_opcode [3] & \control_unit.i_opcode [2]);
  assign _025_ = _024_ | _000_;
  assign _026_ = _011_ | _003_;
  assign _027_ = _026_ | _025_;
  assign \control_unit.o_finish  = _018_ & ~(_027_);
  assign _031_ = ~\pc.clk_cnt [2];
  assign _032_ = \pc.clk_cnt [1] | ~(\pc.clk_cnt [2]);
  assign _033_ = ~((_032_ | \pc.clk_cnt [0]) & _031_);
  assign _028_[0] = ~((_033_ & \pc.i_no_hazard ) | \pc.clk_cnt [0]);
  assign _034_ = ~(\pc.clk_cnt [0] ^ \pc.clk_cnt [1]);
  assign _028_[1] = ~((_033_ & \pc.i_no_hazard ) | _034_);
  assign _035_ = \pc.clk_cnt [0] & \pc.clk_cnt [1];
  assign _036_ = _035_ ^ _031_;
  assign _028_[2] = ~((_033_ & \pc.i_no_hazard ) | _036_);
  assign _037_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [0] : \pc.o_inst_addr [0];
  assign _029_[0] = \pc.i_no_hazard  ? _037_ : \pc.o_inst_addr [0];
  assign _038_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [1] : \pc.o_inst_addr [1];
  assign _029_[1] = \pc.i_no_hazard  ? _038_ : \pc.o_inst_addr [1];
  assign _039_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [2] : \pc.o_inst_addr [2];
  assign _029_[2] = \pc.i_no_hazard  ? _039_ : \pc.o_inst_addr [2];
  assign _040_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [3] : \pc.o_inst_addr [3];
  assign _029_[3] = \pc.i_no_hazard  ? _040_ : \pc.o_inst_addr [3];
  assign _041_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [4] : \pc.o_inst_addr [4];
  assign _029_[4] = \pc.i_no_hazard  ? _041_ : \pc.o_inst_addr [4];
  assign _042_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [5] : \pc.o_inst_addr [5];
  assign _029_[5] = \pc.i_no_hazard  ? _042_ : \pc.o_inst_addr [5];
  assign _043_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [6] : \pc.o_inst_addr [6];
  assign _029_[6] = \pc.i_no_hazard  ? _043_ : \pc.o_inst_addr [6];
  assign _044_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [7] : \pc.o_inst_addr [7];
  assign _029_[7] = \pc.i_no_hazard  ? _044_ : \pc.o_inst_addr [7];
  assign _045_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [8] : \pc.o_inst_addr [8];
  assign _029_[8] = \pc.i_no_hazard  ? _045_ : \pc.o_inst_addr [8];
  assign _046_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [9] : \pc.o_inst_addr [9];
  assign _029_[9] = \pc.i_no_hazard  ? _046_ : \pc.o_inst_addr [9];
  assign _047_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [10] : \pc.o_inst_addr [10];
  assign _029_[10] = \pc.i_no_hazard  ? _047_ : \pc.o_inst_addr [10];
  assign _048_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [11] : \pc.o_inst_addr [11];
  assign _029_[11] = \pc.i_no_hazard  ? _048_ : \pc.o_inst_addr [11];
  assign _049_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [12] : \pc.o_inst_addr [12];
  assign _029_[12] = \pc.i_no_hazard  ? _049_ : \pc.o_inst_addr [12];
  assign _050_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [13] : \pc.o_inst_addr [13];
  assign _029_[13] = \pc.i_no_hazard  ? _050_ : \pc.o_inst_addr [13];
  assign _051_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [14] : \pc.o_inst_addr [14];
  assign _029_[14] = \pc.i_no_hazard  ? _051_ : \pc.o_inst_addr [14];
  assign _052_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [15] : \pc.o_inst_addr [15];
  assign _029_[15] = \pc.i_no_hazard  ? _052_ : \pc.o_inst_addr [15];
  assign _053_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [16] : \pc.o_inst_addr [16];
  assign _029_[16] = \pc.i_no_hazard  ? _053_ : \pc.o_inst_addr [16];
  assign _054_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [17] : \pc.o_inst_addr [17];
  assign _029_[17] = \pc.i_no_hazard  ? _054_ : \pc.o_inst_addr [17];
  assign _055_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [18] : \pc.o_inst_addr [18];
  assign _029_[18] = \pc.i_no_hazard  ? _055_ : \pc.o_inst_addr [18];
  assign _056_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [19] : \pc.o_inst_addr [19];
  assign _029_[19] = \pc.i_no_hazard  ? _056_ : \pc.o_inst_addr [19];
  assign _057_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [20] : \pc.o_inst_addr [20];
  assign _029_[20] = \pc.i_no_hazard  ? _057_ : \pc.o_inst_addr [20];
  assign _058_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [21] : \pc.o_inst_addr [21];
  assign _029_[21] = \pc.i_no_hazard  ? _058_ : \pc.o_inst_addr [21];
  assign _059_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [22] : \pc.o_inst_addr [22];
  assign _029_[22] = \pc.i_no_hazard  ? _059_ : \pc.o_inst_addr [22];
  assign _060_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [23] : \pc.o_inst_addr [23];
  assign _029_[23] = \pc.i_no_hazard  ? _060_ : \pc.o_inst_addr [23];
  assign _061_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [24] : \pc.o_inst_addr [24];
  assign _029_[24] = \pc.i_no_hazard  ? _061_ : \pc.o_inst_addr [24];
  assign _062_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [25] : \pc.o_inst_addr [25];
  assign _029_[25] = \pc.i_no_hazard  ? _062_ : \pc.o_inst_addr [25];
  assign _063_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [26] : \pc.o_inst_addr [26];
  assign _029_[26] = \pc.i_no_hazard  ? _063_ : \pc.o_inst_addr [26];
  assign _064_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [27] : \pc.o_inst_addr [27];
  assign _029_[27] = \pc.i_no_hazard  ? _064_ : \pc.o_inst_addr [27];
  assign _065_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [28] : \pc.o_inst_addr [28];
  assign _029_[28] = \pc.i_no_hazard  ? _065_ : \pc.o_inst_addr [28];
  assign _066_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [29] : \pc.o_inst_addr [29];
  assign _029_[29] = \pc.i_no_hazard  ? _066_ : \pc.o_inst_addr [29];
  assign _067_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [30] : \pc.o_inst_addr [30];
  assign _029_[30] = \pc.i_no_hazard  ? _067_ : \pc.o_inst_addr [30];
  assign _068_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [31] : \pc.o_inst_addr [31];
  assign _029_[31] = \pc.i_no_hazard  ? _068_ : \pc.o_inst_addr [31];
  assign _069_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [32] : \pc.o_inst_addr [32];
  assign _029_[32] = \pc.i_no_hazard  ? _069_ : \pc.o_inst_addr [32];
  assign _070_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [33] : \pc.o_inst_addr [33];
  assign _029_[33] = \pc.i_no_hazard  ? _070_ : \pc.o_inst_addr [33];
  assign _071_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [34] : \pc.o_inst_addr [34];
  assign _029_[34] = \pc.i_no_hazard  ? _071_ : \pc.o_inst_addr [34];
  assign _072_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [35] : \pc.o_inst_addr [35];
  assign _029_[35] = \pc.i_no_hazard  ? _072_ : \pc.o_inst_addr [35];
  assign _073_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [36] : \pc.o_inst_addr [36];
  assign _029_[36] = \pc.i_no_hazard  ? _073_ : \pc.o_inst_addr [36];
  assign _074_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [37] : \pc.o_inst_addr [37];
  assign _029_[37] = \pc.i_no_hazard  ? _074_ : \pc.o_inst_addr [37];
  assign _075_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [38] : \pc.o_inst_addr [38];
  assign _029_[38] = \pc.i_no_hazard  ? _075_ : \pc.o_inst_addr [38];
  assign _076_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [39] : \pc.o_inst_addr [39];
  assign _029_[39] = \pc.i_no_hazard  ? _076_ : \pc.o_inst_addr [39];
  assign _077_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [40] : \pc.o_inst_addr [40];
  assign _029_[40] = \pc.i_no_hazard  ? _077_ : \pc.o_inst_addr [40];
  assign _078_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [41] : \pc.o_inst_addr [41];
  assign _029_[41] = \pc.i_no_hazard  ? _078_ : \pc.o_inst_addr [41];
  assign _079_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [42] : \pc.o_inst_addr [42];
  assign _029_[42] = \pc.i_no_hazard  ? _079_ : \pc.o_inst_addr [42];
  assign _080_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [43] : \pc.o_inst_addr [43];
  assign _029_[43] = \pc.i_no_hazard  ? _080_ : \pc.o_inst_addr [43];
  assign _081_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [44] : \pc.o_inst_addr [44];
  assign _029_[44] = \pc.i_no_hazard  ? _081_ : \pc.o_inst_addr [44];
  assign _082_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [45] : \pc.o_inst_addr [45];
  assign _029_[45] = \pc.i_no_hazard  ? _082_ : \pc.o_inst_addr [45];
  assign _083_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [46] : \pc.o_inst_addr [46];
  assign _029_[46] = \pc.i_no_hazard  ? _083_ : \pc.o_inst_addr [46];
  assign _084_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [47] : \pc.o_inst_addr [47];
  assign _029_[47] = \pc.i_no_hazard  ? _084_ : \pc.o_inst_addr [47];
  assign _085_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [48] : \pc.o_inst_addr [48];
  assign _029_[48] = \pc.i_no_hazard  ? _085_ : \pc.o_inst_addr [48];
  assign _086_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [49] : \pc.o_inst_addr [49];
  assign _029_[49] = \pc.i_no_hazard  ? _086_ : \pc.o_inst_addr [49];
  assign _087_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [50] : \pc.o_inst_addr [50];
  assign _029_[50] = \pc.i_no_hazard  ? _087_ : \pc.o_inst_addr [50];
  assign _088_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [51] : \pc.o_inst_addr [51];
  assign _029_[51] = \pc.i_no_hazard  ? _088_ : \pc.o_inst_addr [51];
  assign _089_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [52] : \pc.o_inst_addr [52];
  assign _029_[52] = \pc.i_no_hazard  ? _089_ : \pc.o_inst_addr [52];
  assign _090_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [53] : \pc.o_inst_addr [53];
  assign _029_[53] = \pc.i_no_hazard  ? _090_ : \pc.o_inst_addr [53];
  assign _091_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [54] : \pc.o_inst_addr [54];
  assign _029_[54] = \pc.i_no_hazard  ? _091_ : \pc.o_inst_addr [54];
  assign _092_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [55] : \pc.o_inst_addr [55];
  assign _029_[55] = \pc.i_no_hazard  ? _092_ : \pc.o_inst_addr [55];
  assign _093_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [56] : \pc.o_inst_addr [56];
  assign _029_[56] = \pc.i_no_hazard  ? _093_ : \pc.o_inst_addr [56];
  assign _094_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [57] : \pc.o_inst_addr [57];
  assign _029_[57] = \pc.i_no_hazard  ? _094_ : \pc.o_inst_addr [57];
  assign _095_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [58] : \pc.o_inst_addr [58];
  assign _029_[58] = \pc.i_no_hazard  ? _095_ : \pc.o_inst_addr [58];
  assign _096_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [59] : \pc.o_inst_addr [59];
  assign _029_[59] = \pc.i_no_hazard  ? _096_ : \pc.o_inst_addr [59];
  assign _097_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [60] : \pc.o_inst_addr [60];
  assign _029_[60] = \pc.i_no_hazard  ? _097_ : \pc.o_inst_addr [60];
  assign _098_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [61] : \pc.o_inst_addr [61];
  assign _029_[61] = \pc.i_no_hazard  ? _098_ : \pc.o_inst_addr [61];
  assign _099_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [62] : \pc.o_inst_addr [62];
  assign _029_[62] = \pc.i_no_hazard  ? _099_ : \pc.o_inst_addr [62];
  assign _100_ = \pc.clk_cnt [2] ? \pc.i_inst_addr [63] : \pc.o_inst_addr [63];
  assign _029_[63] = \pc.i_no_hazard  ? _100_ : \pc.o_inst_addr [63];
  assign _030_ = \pc.i_no_hazard  & \pc.clk_cnt [2];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [0] <= 0;
    else
      \pc.o_inst_addr [0] <= _029_[0];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [1] <= 0;
    else
      \pc.o_inst_addr [1] <= _029_[1];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [2] <= 0;
    else
      \pc.o_inst_addr [2] <= _029_[2];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [3] <= 0;
    else
      \pc.o_inst_addr [3] <= _029_[3];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [4] <= 0;
    else
      \pc.o_inst_addr [4] <= _029_[4];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [5] <= 0;
    else
      \pc.o_inst_addr [5] <= _029_[5];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [6] <= 0;
    else
      \pc.o_inst_addr [6] <= _029_[6];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [7] <= 0;
    else
      \pc.o_inst_addr [7] <= _029_[7];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [8] <= 0;
    else
      \pc.o_inst_addr [8] <= _029_[8];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [9] <= 0;
    else
      \pc.o_inst_addr [9] <= _029_[9];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [10] <= 0;
    else
      \pc.o_inst_addr [10] <= _029_[10];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [11] <= 0;
    else
      \pc.o_inst_addr [11] <= _029_[11];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [12] <= 0;
    else
      \pc.o_inst_addr [12] <= _029_[12];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [13] <= 0;
    else
      \pc.o_inst_addr [13] <= _029_[13];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [14] <= 0;
    else
      \pc.o_inst_addr [14] <= _029_[14];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [15] <= 0;
    else
      \pc.o_inst_addr [15] <= _029_[15];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [16] <= 0;
    else
      \pc.o_inst_addr [16] <= _029_[16];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [17] <= 0;
    else
      \pc.o_inst_addr [17] <= _029_[17];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [18] <= 0;
    else
      \pc.o_inst_addr [18] <= _029_[18];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [19] <= 0;
    else
      \pc.o_inst_addr [19] <= _029_[19];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [20] <= 0;
    else
      \pc.o_inst_addr [20] <= _029_[20];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [21] <= 0;
    else
      \pc.o_inst_addr [21] <= _029_[21];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [22] <= 0;
    else
      \pc.o_inst_addr [22] <= _029_[22];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [23] <= 0;
    else
      \pc.o_inst_addr [23] <= _029_[23];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [24] <= 0;
    else
      \pc.o_inst_addr [24] <= _029_[24];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [25] <= 0;
    else
      \pc.o_inst_addr [25] <= _029_[25];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [26] <= 0;
    else
      \pc.o_inst_addr [26] <= _029_[26];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [27] <= 0;
    else
      \pc.o_inst_addr [27] <= _029_[27];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [28] <= 0;
    else
      \pc.o_inst_addr [28] <= _029_[28];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [29] <= 0;
    else
      \pc.o_inst_addr [29] <= _029_[29];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [30] <= 0;
    else
      \pc.o_inst_addr [30] <= _029_[30];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [31] <= 0;
    else
      \pc.o_inst_addr [31] <= _029_[31];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [32] <= 0;
    else
      \pc.o_inst_addr [32] <= _029_[32];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [33] <= 0;
    else
      \pc.o_inst_addr [33] <= _029_[33];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [34] <= 0;
    else
      \pc.o_inst_addr [34] <= _029_[34];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [35] <= 0;
    else
      \pc.o_inst_addr [35] <= _029_[35];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [36] <= 0;
    else
      \pc.o_inst_addr [36] <= _029_[36];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [37] <= 0;
    else
      \pc.o_inst_addr [37] <= _029_[37];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [38] <= 0;
    else
      \pc.o_inst_addr [38] <= _029_[38];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [39] <= 0;
    else
      \pc.o_inst_addr [39] <= _029_[39];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [40] <= 0;
    else
      \pc.o_inst_addr [40] <= _029_[40];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [41] <= 0;
    else
      \pc.o_inst_addr [41] <= _029_[41];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [42] <= 0;
    else
      \pc.o_inst_addr [42] <= _029_[42];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [43] <= 0;
    else
      \pc.o_inst_addr [43] <= _029_[43];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [44] <= 0;
    else
      \pc.o_inst_addr [44] <= _029_[44];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [45] <= 0;
    else
      \pc.o_inst_addr [45] <= _029_[45];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [46] <= 0;
    else
      \pc.o_inst_addr [46] <= _029_[46];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [47] <= 0;
    else
      \pc.o_inst_addr [47] <= _029_[47];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [48] <= 0;
    else
      \pc.o_inst_addr [48] <= _029_[48];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [49] <= 0;
    else
      \pc.o_inst_addr [49] <= _029_[49];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [50] <= 0;
    else
      \pc.o_inst_addr [50] <= _029_[50];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [51] <= 0;
    else
      \pc.o_inst_addr [51] <= _029_[51];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [52] <= 0;
    else
      \pc.o_inst_addr [52] <= _029_[52];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [53] <= 0;
    else
      \pc.o_inst_addr [53] <= _029_[53];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [54] <= 0;
    else
      \pc.o_inst_addr [54] <= _029_[54];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [55] <= 0;
    else
      \pc.o_inst_addr [55] <= _029_[55];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [56] <= 0;
    else
      \pc.o_inst_addr [56] <= _029_[56];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [57] <= 0;
    else
      \pc.o_inst_addr [57] <= _029_[57];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [58] <= 0;
    else
      \pc.o_inst_addr [58] <= _029_[58];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [59] <= 0;
    else
      \pc.o_inst_addr [59] <= _029_[59];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [60] <= 0;
    else
      \pc.o_inst_addr [60] <= _029_[60];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [61] <= 0;
    else
      \pc.o_inst_addr [61] <= _029_[61];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [62] <= 0;
    else
      \pc.o_inst_addr [62] <= _029_[62];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_inst_addr [63] <= 0;
    else
      \pc.o_inst_addr [63] <= _029_[63];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.o_valid_inst_addr  <= 1;
    else
      \pc.o_valid_inst_addr  <= _030_;
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.clk_cnt [0] <= 0;
    else
      \pc.clk_cnt [0] <= _028_[0];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.clk_cnt [1] <= 0;
    else
      \pc.clk_cnt [1] <= _028_[1];
  always @(posedge \pc.i_clk  or negedge \pc.i_rst_n )
    if (!\pc.i_rst_n )
      \pc.clk_cnt [2] <= 0;
    else
      \pc.clk_cnt [2] <= _028_[2];
  assign \IDEX.o_inst  = 1'hx;
  assign \IDEX.o_memRead  = 1'hx;
  assign \IDEX.o_memToReg  = 1'hx;
  assign \IDEX.o_memWrite  = 1'hx;
  assign \IDEX.o_regWrite  = 1'hx;
  assign \IFID.o_next_inst  = 1'hx;
  assign \alu.o_data  = 1'hx;
  assign \alu_data1_choose.o_data  = 1'hx;
  assign \forwardB.o_data  = 1'hx;
  assign \hazard_detector.o_hazard  = 1'hx;
  assign \hazard_detector.o_nop  = 1'hx;
  assign o_d_r_addr = o_d_addr;
  assign o_d_w_addr = o_d_addr;
  assign \pc_choose.o_data  = 1'hx;
  assign \pc.i_change  = 1'hx;
  assign \pc.i_clk  = i_clk;
  assign \pc.i_inst_addr  = 64'b000000000000000000000000000000000000000000000000000000000000000x;
  assign \pc.i_no_hazard  = 1'hx;
  assign \pc.i_rst_n  = i_rst_n;
  assign o_i_addr = \pc.o_inst_addr ;
  assign o_i_valid_addr = \pc.o_valid_inst_addr ;
  assign \control_unit.i_nop  = 1'hx;
  assign \control_unit.i_opcode  = 7'hxx;
  assign o_finish = \control_unit.o_finish ;
  assign \control_unit.o_memToReg  = \control_unit.o_memRead ;
  assign \EXMEM.i_alu_data1  = 64'b000000000000000000000000000000000000000000000000000000000000000x;
  assign \EXMEM.i_alu_out  = 64'b000000000000000000000000000000000000000000000000000000000000000x;
  assign \EXMEM.i_clk  = i_clk;
  assign \EXMEM.i_inst  = 32'b0000000000000000000000000000000x;
  assign \EXMEM.i_memRead  = 1'hx;
  assign \EXMEM.i_memToReg  = 1'hx;
  assign \EXMEM.i_memWrite  = 1'hx;
  assign \EXMEM.i_rd_addr  = 5'hxx;
  assign \EXMEM.i_regWrite  = 1'hx;
  assign \EXMEM.i_rs2_data  = 64'b000000000000000000000000000000000000000000000000000000000000000x;
  assign \EXMEM.i_rst_n  = i_rst_n;
  assign o_d_addr = \EXMEM.o_alu_out ;
  assign o_d_MemRead = \EXMEM.o_memRead ;
  assign o_d_MemWrite = \EXMEM.o_memWrite ;
  assign o_d_w_data = \EXMEM.o_rs2_data ;
endmodule
